name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.25.0"
      - name: Run lint
        run: |
          deno lint
      - name: Run tests
        run: |
          deno test -A